# Generated by Django 5.1.6 on 2025-02-10 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('firmName', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('weburl', models.URLField()),
                ('des', models.TextField()),
                ('linkedin', models.URLField()),
                ('reg_no', models.IntegerField()),
                ('reg_certificate', models.FileField(upload_to='media/certificates')),
                ('year_founded', models.IntegerField()),
                ('teamSize', models.IntegerField()),
                ('businessPlan', models.FileField(upload_to='media/businessplan')),
                ('pitchVideos', models.FileField(blank=True, null=True, upload_to='media/pitchvideos')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
