# Generated by Django 5.1.6 on 2025-02-10 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='reg_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='startup',
            name='reg_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
