# Generated by Django 5.1.6 on 2025-02-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseform', '0002_investor_reg_date_startup_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='inverstorname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
